### ISSUE TITLE
Week 3 Review Ticket - Prisha Maiti

### ISSUE THREAD

**Issue by PrishaMaiti** [PrishaMaiti/DataStructures#3]
# Total Score: 4.4/5, Grader: Jonathan Lin
Team Score: 2.5/3
Individual Score: 1.9/2

Replit: https://replit.com/@PrishaMaiti/DataStructures#Main.java
GitHub Pages: https://prishamaiti.github.io/DataStructures/
Team Repository: https://github.com/dsblack0/stickers_for_charity
Team GitHub Pages: https://dsblack0.github.io/stickers_for_charity/
(Note: Calculator page is part of the Code Snippets page where I have an explanation for the different methods and snippets of each written method of Calculator.java)
(Note: I excluded the given test cases on Replit so that user gets liberty of choosing any expression to be evaluated using the Scanner, not just limited to the provided test cases. If user wishes, they can type the expressions of the given test cases shown before the Scanner on CalculatorTester.java in the console that have been commented out)
Individual GitHub Pages (2 points)
GitHub review page that documents key learnings using code snippets
- [x] Calculator page that shows highlights of work .5
- [x] Calculator Code with optional extra credit functions, Replit Runtime, with runnable (no input) Test Data, and input option. 1.5

**Comment by armarmgc** [comment]
# Total 4.4/5, Grader: Jonathan Lin

Team 2.5/3
.5/1 - Project Owner / Sponsor presentation and results of review
Participated in Team Review, but no notes or actions taken.
1/1 - 1st Code in GitHub
Has many [commits](https://github.com/dsblack0/stickers_for_charity/commits?author=PrishaMaiti) in the team github repo.
Has [tickets](https://github.com/dsblack0/stickers_for_charity/issues) with tangibles.
1/1 - 1st Deployment, including hosting plan in GitHub pages

Individual 1.9/2
.4/.5 - Calculator page with [highlights of work](https://github.com/PrishaMaiti/DataStructures/blob/main/Code_Explanations.md#calculator) done, but not on Jekyll pages because of build errors.

1.5/1.5 - Calculator Code
[Calculator](https://replit.com/@PrishaMaiti/DataStructures#Calculator.java) takes input and shows the RPN process. All required calculator operators are implemented.
