### ISSUE TITLE
Crossover Grading for Prisha Study Week 1

### ISSUE THREAD

**Issue by PrishaMaiti** [PrishaMaiti/DataStructures#7]
https://prishamaiti.github.io/DataStructures/

All tangibles (Replit, 2015 MCQ corrections page, 2015 FRQ page, etc.) are on the Jekyll link

2015 FRQs on Menu are keyboard input options 10-12

**Comment by wrachel** [comment]
Crossover Grading: 
1/1 Study plan for week, due EOD Monday: is mentioned [here](https://prishamaiti.github.io/DataStructures/AP_Exam_Prep_Plans)
* Study plan is very thorough, has 3 outlined steps with guiding questions for her future work and steps to complete each of her goals.

MCQ results and corrections: [linked here](https://prishamaiti.github.io/DataStructures/2015MCQCorrections)
* 1/1 Score is above 50%, Corrections for each problem is included. She explains why the correct answer is correct.
 
FRQs in REPL and peer review
* 0.9/1 FRQS are running in REPL [LINKED HERE](https://replit.com/@PrishaMaiti/DataStructures#Main.java) and are inputs 10-12 and work as intended
* Thorough code for each of the questions can be found on REPL
* Took off 0.1 because missing implementation for one of the FRQ Questions

Individual Self Study guide
* 1/1 [Study Guide is linked here](https://prishamaiti.github.io/DataStructures/SelfStudyGuide)
* Links take you to thorough notes from learning from AP practice this week

Crossover Grade and Score
1/1: She graded Maggie Killada, and did so thoroughly and fairly
* She noticed when certain FRQs were missing or corrections were missing and took off points accordingly

Total Score: 4.9/5

**Comment by PrishaMaiti** [comment]
Total Score (initial, up to 4.5): 2.75/4.5
GitHub Page for Study Plan for all weeks is there, including current week, and is timeboxed. Tangible evidence: https://maggie3000.github.io/CSAindividualrepoTRI3/testprep (1/1)
MCQ results and corrections are only there for the 5 missed questions out of the first 20, which were the only ones attempted. Tangible evidence: https://docs.google.com/document/d/1hnGSegc8mK6UaCFb44g5pyID2GeBi-jdH1bRH9I9wpU/edit (0.5/1)
https://docs.google.com/document/d/1ozX2GZrF5EtjjACN-d-MyPuIS8Tapc3czkGSVk8OEC0/edit Original attempt of FRQs are there. https://github.com/maggie3000/CSAindividualrepoTRI3/blob/master/frq/DiverseArray.java This is what was shown for Repl, which isn't a Replit link. She only has FRQ for the first question, DiverseArray, working on Repl. (.25/1)
Study Guide: https://maggie3000.github.io/CSAindividualrepoTRI3/studyguide All 10 units are there and organized with thorough notes. (1/1)
